version: "3.5"
services:
  siberiumlab-geth.dnp.dappnode.eth:
    image: "siberiumlab-geth.dnp.dappnode.eth:0.1.1"
    build:
      context: .
      args:
        UPSTREAM_VERSION: v1.11.6
    volumes:
      - "siberiumlab:/siberiumlab"
    ports:
      - "30001:30001/tcp"
      - "30001:30001/udp"
    restart: unless-stopped
    environment:
      - "EXTRA_OPTION=--http.api eth,engine,net,web3,txpool"
      - P2P_PORT=30001
      - SYNCMODE
volumes:
  siberiumlab: {}
